### ISSUE TITLE
Rewrite Docker documentation to use Docker Volumes instead folders

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/Core#732]
При использовании Docker для управления настройками и данными контейнеров, у вас действительно есть несколько вариантов: монтирование директорий хоста, создание volumes, и использование отдельных контейнеров с volume. Каждый из этих вариантов имеет свои плюсы и минусы, и выбор оптимального подхода зависит от ваших конкретных потребностей и сценариев использования.

Варианты и их особенности:
### Монтирование директорий хоста (bind mount):

**Плюсы:**

- Легко настраивается.
- Данные сразу видны на хосте.

**Минусы:**

- Проблемы с переносимостью: если контейнеры запускаются на других хостах, директории могут отсутствовать.
- Потенциальные проблемы с безопасностью, так как контейнеры получают полный доступ к файловой системе хоста.

### Создание volumes:

**Плюсы:**

- Volumes управляются Docker, что улучшает переносимость.
- Поддерживаются бэкапы, миграции и другие операции.
- Более высокая производительность по сравнению с bind mounts.

**Минусы:**

- Данные хранятся в специфичных для Docker директориях, что усложняет прямой доступ к ним с хоста.
 
### Использование отдельных контейнеров с volumes:

**Плюсы:**

- Удобно для совместного использования данных между несколькими контейнерами.
- Легче управлять данными и обновлениями.

**Минусы:**

- Усложняет инфраструктуру.

**Рекомендация**
Для вашего случая, если необходимо иметь две папки /cf и /storage, наиболее оптимальным и переносимым вариантом будет использование volumes. Это обеспечивает лучшую управляемость и производительность.

### Пример конфигурации
Можно использовать один volume для обеих папок. В Docker Compose это может выглядеть следующим образом:

```yaml
version: '3.8'
services:
  your_service:
    image: your_image
    volumes:
      - data_volume:/cf
      - data_volume:/storage

volumes:
  data_volume:
```

Такой подход создаст один volume data_volume, который будет смонтирован в обе директории /cf и /storage внутри контейнера.

**Пример с использованием Dockerfile и командной строки**
Если не используете Docker Compose, это можно сделать с помощью командной строки:

```sh
docker volume create data_volume
docker run -d --name your_container \
  -v data_volume:/cf \
  -v data_volume:/storage \
  your_image
```

Docker Compose файл:

```yaml
version: '3.8'
services:
  your_service:
    image: your_image  # Image of your container
    volumes:
      - data_volume:/cf  # Mounting the volume to /cf
      - data_volume:/storage  # Mounting the same volume to /storage

volumes:
  data_volume:  # Defining the named volume
```
Команды для создания и запуска контейнера:

```sh
docker volume create data_volume  # Creating a named volume called data_volume

docker run -d --name your_container \
  -v data_volume:/cf  # Mounting the volume to /cf
  -v data_volume:/storage  # Mounting the same volume to /storage
  your_image  # Name of your image

```
Такой подход обеспечит, что ваши данные будут храниться в одном месте и будут доступны контейнеру в нужных директориях.

Надо проверить и переписать инструкции на Volumes
