### ISSUE TITLE
Got readonly database error when changing admin password

### ISSUE THREAD

**Issue by bagus-repository** [mikopbx/Core#768]
I am installing MikoPBX using docker compose file, this is the docker compose I used
```
services:
  mikopbx:
    container_name: "mikopbx"
    image: "ghcr.io/mikopbx/mikopbx-x86-64"
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    entrypoint: "/sbin/docker-entrypoint"
    hostname:  "mikopbx-in-a-docker"
    volumes:
      - data_volume:/cf
      - data_volume:/storage
    tty: true
    environment:
      # Change the station name through environment variables
      - PBX_NAME=MikoPBX-in-Docker
      # Change the default SSH port to 23
      - SSH_PORT=23
      # Change the default WEB port to 8080
      - WEB_PORT=8080
      # Change the default WEB HTTPS port to 8443
      - WEB_HTTPS_PORT=8443
      - REDIS_PORT=7379
volumes:
  data_volume
```
When logged in web UI and requested to change admin password I got error:
```
PDOException: SQLSTATE[HY000]: General error: 8 attempt to write a readonly database in file /offload/rootfs/usr/www/src/Common/Models/PbxSettings.php on line 263 Stack trace: 1. PDOException->() /offload/rootfs/usr/www/src/Common/Models/PbxSettings.php:263 2. Phalcon\Mvc\Model->save() /offload/rootfs/usr/www/src/Common/Models/PbxSettings.php:263 3. MikoPBX\Common\Models\PbxSettings->setValue() /offload/rootfs/usr/www/src/AdminCabinet/Controllers/GeneralSettingsController.php:309 4. MikoPBX\AdminCabinet\Controllers\GeneralSettingsController->updatePBXSettings() /offload/rootfs/usr/www/src/AdminCabinet/Controllers/GeneralSettingsController.php:127 5. MikoPBX\AdminCabinet\Controllers\GeneralSettingsController->saveAction() [internal]:0 6. Phalcon\Dispatcher\AbstractDispatcher->callActionMethod() [internal]:0 7. Phalcon\Dispatcher\AbstractDispatcher->dispatch() [internal]:0 8. Phalcon\Mvc\Application->handle() /offload/rootfs/usr/www/sites/admin-cabinet/index.php:65 9. Application->main() /offload/rootfs/usr/www/sites/admin-cabinet/index.php:73 PDOException: SQLSTATE[HY000]: General error: 8 attempt to write a readonly database in file /offload/rootfs/usr/www/src/Common/Models/PbxSettings.php on line 263 Stack trace: 1. PDOException->() /offload/rootfs/usr/www/src/Common/Models/PbxSettings.php:263 2. Phalcon\Mvc\Model->save() /offload/rootfs/usr/www/src/Common/Models/PbxSettings.php:263 3. MikoPBX\Common\Models\PbxSettings->setValue() /offload/rootfs/usr/www/src/AdminCabinet/Controllers/GeneralSettingsController.php:309 4. MikoPBX\AdminCabinet\Controllers\GeneralSettingsController->updatePBXSettings() /offload/rootfs/usr/www/src/AdminCabinet/Controllers/GeneralSettingsController.php:127 5. MikoPBX\AdminCabinet\Controllers\GeneralSettingsController->saveAction() [internal]:0 6. Phalcon\Dispatcher\AbstractDispatcher->callActionMethod() [internal]:0 7. Phalcon\Dispatcher\AbstractDispatcher->dispatch() [internal]:0 8. Phalcon\Mvc\Application->handle() /offload/rootfs/usr/www/sites/admin-cabinet/index.php:65 9. Application->main() /offload/rootfs/usr/www/sites/admin-cabinet/index.php:73 {"error":{"type":"PDOException","message":"SQLSTATE[HY000]: General error: 8 attempt to write a readonly database","code":"HY000","file":"\/offload\/rootfs\/usr\/www\/src\/Common\/Models\/PbxSettings.php","line":263}}
```
